SumanthInPaylocity/Models/DependentVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SIP.Entities.Enums;

namespace SumanthInPaylocity.Models
{
    public class DependentVM : PersonVM
    {
        public List<SelectListItem> TypeList { get; set; }
       
    }
}

SumanthInPaylocity/Models/EmployeeVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SumanthInPaylocity.Models
{
    public class EmployeeVM : PersonVM
    {
        public EmployeeVM()
        {
            Dependents = new List<DependentVM>();
        }
        public List<DependentVM> Dependents { get; set; }
    }
}

SumanthInPaylocity/Models/PersonVM.cs
using SIP.Entities.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SumanthInPaylocity.Models
{
    public class PersonVM
    {
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public EntityTypes Type { get; set; }
    }
}

SumanthInPaylocity/Models/ResultsVM.cs
using System.ComponentModel.DataAnnotations;

namespace SumanthInPaylocity.Models
{
    public class ResultsVM
    {
        [DisplayFormat(DataFormatString = "{0:C2}")]
        [Display(Name = "Totals")]
        public decimal TotalPayCheckDeductions { get; set; }

        [DisplayFormat(DataFormatString = "{0:C2}")]
        public decimal TotalFinalPayCheckDeductions { get; set; }

        [DisplayFormat(DataFormatString = "{0:C2}")]
        public decimal TotalYearlyDeductions { get; set; }



        [DisplayFormat(DataFormatString = "{0:C2}")]
        [Display(Name = "Employee")]
        public decimal EmployeePayCheckDeductions { get; set; }
        [DisplayFormat(DataFormatString = "{0:C2}")]
        public decimal EmployeeFinalPayCheckDeductions { get; set; }

        [DisplayFormat(DataFormatString = "{0:C2}")]
        public decimal EmployeeYearlyDeductions { get; set; }



        [DisplayFormat(DataFormatString = "{0:C2}")]
        public decimal DependentsYearlyDeductions { get; set; }

        [DisplayFormat(DataFormatString = "{0:C2}")]
        [Display(Name = "Dependents")]
        public decimal DependentsPayCheckDeductions { get; set; }
        [DisplayFormat(DataFormatString = "{0:C2}")]
        public decimal DependentsFinalPayCheckDeductions { get; set; }



        [DisplayFormat(DataFormatString = "{0:C2}")]
        [Display(Name = "Pay Check After Deductions")]
        public decimal DeductedPayCheck { get; set; } 

        [DisplayFormat(DataFormatString = "{0:C2}")]

        [Display(Name = "Final Pay Check After Deductions")]
        public decimal DeductedFinalPayCheck { get; set; } 

        [DisplayFormat(DataFormatString = "{0:C2}")]

        [Display(Name = "Yearly Pay After Deductions")]
        public decimal DeductedYearlyPayCheck { get; set; }

    }
}

SumanthInPaylocity/Controllers/CalculateDeductionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using SIP.Entities;
using SIP.Business.Services;
using SumanthInPaylocity.Models;
using SIP.Entities.Enums;

namespace SumanthInPaylocity.Controllers
{
    public class CalculateDeductionsController : Controller
    {
        private readonly Lazy<IGetCalculations> _getCalculations;

        public CalculateDeductionsController(Lazy<IGetCalculations> getCalculations)
        {
            _getCalculations = getCalculations;
        }

        public ActionResult EmployeeEntry()
        {
            var employee = new EmployeeVM
            {
                Type = EntityTypes.Employee
            };

            return View(employee);
        }

        [HttpPost]
        public ActionResult EmployeeEntry(EmployeeVM model)
        {
            if (!ModelState.IsValid)
            {
                if(model.Dependents.Count > 0)
                {
                    var items = GetTypeListItems().ToList();
                    model.Dependents.ForEach(x => x.TypeList = items);
                }
                return View("EmployeeEntry", model);
            }

            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<EmployeeVM, Employee>();
                cfg.CreateMap<DependentVM, Dependent>();
                cfg.CreateMap<PersonVM, Person>();

            });
            var mapper = new Mapper(config);
            var entityBusinessModel = mapper.Map<Employee>(model);

            var service = _getCalculations.Value;

            var responseModel = new ResultsVM();
            //Employee deductions 
            responseModel.EmployeePayCheckDeductions = service.GetEmployeePayCheckDeductions(entityBusinessModel);
            responseModel.EmployeeYearlyDeductions = service.GetEmployeeYearlyDeductions(entityBusinessModel);
            responseModel.EmployeeFinalPayCheckDeductions = service.GetFinalPayCheckDeductions(responseModel.EmployeePayCheckDeductions, responseModel.EmployeeYearlyDeductions);

            //Dependents Deductions
            responseModel.DependentsPayCheckDeductions = service.GetDependentPayCheckDeductions(entityBusinessModel.Dependents);
            responseModel.DependentsYearlyDeductions = service.GetDependentYearlyPayCheckDeductions(entityBusinessModel.Dependents);
            responseModel.DependentsFinalPayCheckDeductions = service.GetFinalPayCheckDeductions(responseModel.DependentsPayCheckDeductions, responseModel.DependentsYearlyDeductions);

            //Total Deductions
            responseModel.TotalPayCheckDeductions = responseModel.EmployeePayCheckDeductions + responseModel.DependentsPayCheckDeductions;
            responseModel.TotalYearlyDeductions = responseModel.EmployeeYearlyDeductions + responseModel.DependentsYearlyDeductions;
            responseModel.TotalFinalPayCheckDeductions = responseModel.EmployeeFinalPayCheckDeductions + responseModel.DependentsFinalPayCheckDeductions;

            //Paycheck Details
            responseModel.DeductedPayCheck = service.GetPaycheckAfterDeductions(responseModel.TotalPayCheckDeductions);
            responseModel.DeductedFinalPayCheck = service.GetPaycheckAfterDeductions(responseModel.TotalFinalPayCheckDeductions);
            responseModel.DeductedYearlyPayCheck = service.GetYearlyPaycheckAfterDeductions(responseModel.TotalYearlyDeductions);



            return View("Results", responseModel);
        }

        public ActionResult AddNewDependent()
        {
            var dependent = new DependentVM();

            dependent.TypeList = GetTypeListItems().ToList();
            return PartialView("_Dependents", dependent);
        }

        private IEnumerable<SelectListItem> GetTypeListItems()
        {
            return from EntityTypes d in Enum.GetValues(typeof(EntityTypes))
                   where d != EntityTypes.Employee
                   select new SelectListItem
                   {
                       Text = d.ToString(),
                       Value = Convert.ToInt32(d).ToString()
                   };
        }
    }
}

SumanthInPaylocity/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using SIP.Entities;
using SIP.Business.Services;
using SumanthInPaylocity.Models;

namespace SumanthInPaylocity.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Sumanth Reddy M";
            return View();
        }


    }
}

SumanthInPaylocity/Views/CalculateDeductions/EmployeeEntry.cshtml
@model SumanthInPaylocity.Models.EmployeeVM
@{
    ViewBag.Title = "Employee Information";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2 class="text-justify">Employee Information</h2>
@using (Html.BeginForm("EmployeeEntry", "CalculateDeductions"))
{
    <p class="text-info">
       Enter the employee's information along with dependent's information, if any, to see the deductions 
    </p>
    <div class="row">
        <div class="form-group col-lg-3" style="padding-top:7px;">       
            <text style="font-weight:bold" >Employee Information</text>
        </div>
        <div class="form-group col-lg-3"> 
            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", @placeholder = "First Name" })
            @Html.ValidationMessageFor(m => m.FirstName, null, new { @class = "text-danger" })
        </div>
        <div class="form-group col-lg-3"> 
            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", @placeholder = "Last Name" })
            @Html.ValidationMessageFor(m => m.LastName, null, new { @class = "text-danger" })
        </div>
        @Html.HiddenFor(m => m.Type)
    </div>
    <div class="form-group">
        <br />
        <p style="font-weight:bolder">Dependents Information</p>
    </div>

    <fieldset>
        <div id="new-Dependent">
            @foreach (var dependent in Model.Dependents)
            {
                Html.RenderPartial("~/Views/CalculateDeductions/_Dependents.cshtml", dependent);
            }

        </div>
        <div class="form-group">
            <br />
            <input type="button" class="btn btn-primary" id="adddependent" name="adddependent" value="Add Dependent" />
            <br />
        </div>
        <br />
        <div>
            <button class="btn btn-success" type="submit">Calculate Costs & Deductions </button>
        </div>
    </fieldset>

    @section Scripts
            {
        <script type="text/javascript">
                    $('#adddependent').on('click',
                        function () {
                            $.ajax({
                                async: false,
                                url: '/CalculateDeductions/AddNewDependent'
                            }).done(function (partialView) {
                                $('#new-Dependent').append(partialView);
                            });
                        });

                    $(document).on('click', '#deleteRow',
                        function deleteDependent () {
                            var container = $(this).closest('.dependentRow');
                            container.remove();
                        });

        </script>
    }
}

SumanthInPaylocity/Views/CalculateDeductions/Results.cshtml
@model SumanthInPaylocity.Models.ResultsVM

@{
    ViewBag.Title = "Employee Deductions and Costs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 

<div>
    <h2 class="text-center">Employee Deductions and Costs</h2>
    <hr />
    <dl class="dl-horizontal"></dl>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col"> </th>
                <th scope="col">PayCheck Deductions</th>
                <th scope="col">Yearly Deductions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">
                    @Html.LabelFor(m => m.EmployeePayCheckDeductions)
                </th>
                <td>
                    @Html.DisplayFor(m => m.EmployeePayCheckDeductions) @if (@Model.EmployeeFinalPayCheckDeductions > 0m)
                    {<text> ( Final Pay Check Deduction:  @Html.DisplayFor(m => m.EmployeeFinalPayCheckDeductions) ) </text>}
                </td>
                <td>
                    @Html.DisplayFor(m => m.EmployeeYearlyDeductions)
                </td>
            </tr>
            @if (Model.DependentsPayCheckDeductions != 0m && Model.DependentsYearlyDeductions != 0m)
            {
            <tr>
                <th scope="row">
                    @Html.LabelFor(m => m.DependentsPayCheckDeductions)
                </th>
                <td>
                    @Html.DisplayFor(m => m.DependentsPayCheckDeductions)  @if (@Model.DependentsFinalPayCheckDeductions > 0m)
                    {<text> ( Final Pay Check Deduction: @Html.DisplayFor(m => m.DependentsFinalPayCheckDeductions) ) </text>}
                </td>
                <td>
                    @Html.DisplayFor(m => m.DependentsYearlyDeductions)
                </td>
            </tr>
            }
            <tr>
                <th scope="row">
                    @Html.LabelFor(m => m.TotalPayCheckDeductions)
                </th>
                <td>
                    @Html.DisplayFor(m => m.TotalPayCheckDeductions)   @if (@Model.TotalFinalPayCheckDeductions > 0m)
                    {<text> ( Final Pay Check Deduction: @Html.DisplayFor(m => m.TotalFinalPayCheckDeductions) ) </text>}
                </td>
                <td>
                    @Html.DisplayFor(m => m.TotalYearlyDeductions)
                </td>
            </tr>
        </tbody>
    </table>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                @Html.LabelFor(m => m.DeductedPayCheck)
            </div>
            <div class="col-lg-2">
                @Html.DisplayFor(m => m.DeductedPayCheck)
            </div>
        </div>

        @if (@Model.DeductedFinalPayCheck > 0m)
        {
            <div class="row">
                <div class="col-lg-3">
                    @Html.LabelFor(m => m.DeductedFinalPayCheck)
                </div>
                <div class="col-lg-2">
                    @Html.DisplayFor(m => m.DeductedFinalPayCheck)
                </div>
            </div>
        }

        <div class="row">
            <div class="col-lg-3">
                @Html.LabelFor(m => m.DeductedYearlyPayCheck)
            </div>
            <div class="col-lg-2">
                @Html.DisplayFor(m => m.DeductedYearlyPayCheck)
            </div>
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Back to Employee Information Entry", "EmployeeEntry")
</p>

SumanthInPaylocity/Views/CalculateDeductions/_Dependents.cshtml
@using SIP.Entities.Enums
@model SumanthInPaylocity.Models.DependentVM

@using (Html.BeginCollectionItem("Dependents"))
{
    <div class="row">
        <div id="dependentRow" class="dependentRow">
            <div class="form-group">
                <div class="col-lg-3">
                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", @placeholder = "First Name" })
                    @Html.ValidationMessageFor(m => m.FirstName, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-3">
                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", @placeholder = "Last Name" })
                    @Html.ValidationMessageFor(m => m.LastName, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-3">
                    @Html.DropDownListFor(model => model.Type, new SelectList(Model.TypeList, "Value", "Text") , "Select Type", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Type, null, new { @class = "text-danger" })               
                </div>
            </div> 
            <div class="form-group">
                <div class="col-lg-3">
                    <input type="button" class="btn btn-danger" id="deleteRow" name="deleteRow" value="Cancel" />

                </div>
            </div>
        </div>

    </div>
}

SumanthInPaylocity/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<address>
    817 Windbreeze Dr<br />
    Toledo, OH 43615<br />
</address>

<address>
    <strong>Email:</strong>   <a href="mailto:sumanthreddy2022@gmail.com">sumanthreddy2022@gmail.com</a><br /> 
</address>

SumanthInPaylocity/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Paylocity Coding Challenge";
}

<div class="jumbotron">
    <h1>Paylocity Coding Challenge</h1>
    <p class="lead"> Application to check the deductions of employee and dependents. </p> 
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Employee</h2>
        <p />
        Main entity, with a salary of $2000 per paycheck before deductions. There are 26 paychecks in a year.
        The cost of benefits is $1000/year for each employee
        </p>
    </div>
    <div class="col-md-4">
        <h2>Dependents</h2>
        <p>Each dependent (children and possibly spouses) incurs a cost of $500/year</p> 
    </div>
    <div class="col-md-4">
        <h2>Discounts</h2>
        <p>Anyone whose name starts with ‘A’ gets a 10% discount, employee or dependent. Main assumption here is it can be a first or last name</p> 
    </div>
</div>

SumanthInPaylocity/Views/Shared/EditorTemplates/Collection.cshtml
@using HtmlHelpers.BeginCollectionItem

<ul>                                 
    @foreach (object item in Model)
    {
        <li>
            @using (Html.BeginCollectionItem(Html.ViewData.TemplateInfo.HtmlFieldPrefix))
            {
                @Html.EditorFor(_ => item, null, "")
            }
        </li>
    }
</ul>

SumanthInPaylocity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Paylocity Coding Challenge </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span> 
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Paylocity Coding Challenge", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Employee Information", "EmployeeEntry", "CalculateDeductions")</li> 
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -Paylocity </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>